typescript_sources(
    sources=["api.ts", "config.ts", "format.ts", "markdown.ts", "tags.ts", "theme.ts"],
)

typescript_tests(
    name="tests",
    sources=["api.test.ts", "config.test.ts", "markdown.test.ts", "tags.test.ts"],
)
