version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    labels:
      - ci

  - package-ecosystem: 'terraform'
    directory: '/infrastructure'
    schedule:
      interval: 'weekly'
    labels:
      - infrastructure

  - package-ecosystem: 'npm'
    directory: '/services/frontend'
    schedule:
      interval: 'weekly'
    labels:
      - frontend

  - package-ecosystem: 'gomod'
    directory: '/services/backend'
    schedule:
      interval: 'weekly'
    labels:
      - backend
