version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    labels:
      - ci
    groups:
      ci-deps:
        patterns:
          - '*'

  - package-ecosystem: 'terraform'
    directory: '/infrastructure/env'
    schedule:
      interval: 'weekly'
    labels:
      - infrastructure
    groups:
      terraform-deps:
        patterns:
          - '*'

  - package-ecosystem: 'npm'
    directory: '/services/frontend'
    schedule:
      interval: 'weekly'
    labels:
      - frontend
    groups:
      npm-deps:
        patterns:
          - '*'

  - package-ecosystem: 'gomod'
    directory: '/services/backend'
    schedule:
      interval: 'weekly'
    labels:
      - backend
    groups:
      gomod-deps:
        patterns:
          - '*'
