import { Link } from 'react-router-dom'
import { PageMeta } from '../components/PageMeta'

const ISSUES_URL = 'https://github.com/edgorman/blog.gorman.club/issues'

/** The terms of service (#239). Static text: a change to what it describes changes this page too. */
export function Terms() {
  return (
    <div className="page">
      <PageMeta title="Terms of service" description="The terms for using the Gorman Club blog." path="/terms" />
      <header className="page-header">
        <span className="page-kicker text-muted">Legal</span>
        <h1 className="title-post">Terms of service</h1>
        <p className="text-muted">Last updated 28 September 2026</p>
      </header>

      <div className="post-body">
        <p>
          These terms apply to anyone who uses blog.gorman.club. Signing in creates an account, and by creating one
          you agree to these terms and to the <Link to="/privacy">privacy policy</Link>.
        </p>

        <h2>Accounts</h2>
        <p>
          You sign in with your Google account. Keep to one account per person. The maintainer may suspend or delete
          an account that breaks these terms.
        </p>

        <h2>Your content</h2>
        <p>
          You keep ownership of the posts and comments you publish. By publishing them you grant the site a
          non-exclusive, royalty-free licence to store, display and process them for as long as they are on the site.
          Processing includes sending them to Google's Gemini models to build search and related-post embeddings and
          to moderate comments. The licence ends when you delete the content or your account.
        </p>

        <h2>Acceptable use</h2>
        <p>Do not publish anything that is illegal, harasses someone, is spam, or impersonates another person.</p>
        <p>
          Moderation, automated or by the maintainer, may hide or remove content that breaks these rules. To report
          content, open an issue on <a href={ISSUES_URL}>GitHub</a>.
        </p>

        <h2>AI writing assistant</h2>
        <p>
          The assistant's output is generated by AI and may be inaccurate or incomplete. Check it before you publish:
          once published, it is your content like anything else you write. Drafts you share with the assistant are
          sent to Google's Vertex AI to generate a reply. Usage limits apply, and requests over them are refused
          until the limit resets.
        </p>

        <h2>Subscription</h2>
        <p>
          The assistant is sold as a single recurring subscription through Stripe. The price and billing period are
          shown on the Stripe checkout page before you pay, and the subscription renews automatically at the end of
          each period until you cancel it.
        </p>
        <p>
          You can cancel at any time from the billing portal linked on your profile. Cancelling stops the next renewal;
          you keep access until the end of the period you have already paid for, and then it ends. If a renewal
          payment fails, access continues while Stripe retries it and ends if the payment does not go through.
        </p>
        <p>
          If you are a consumer in the UK or EU you normally have 14 days to cancel a digital service and get a
          refund. Because the assistant is available immediately, at checkout you ask for access to start straight
          away and acknowledge that you lose that right once it does. Apart from that, payments are not refunded,
          including for part of a period, unless the law requires it.
        </p>

        <h2>Disclaimers and liability</h2>
        <p>
          This is a demo project run by one person and is provided as is, without warranties of any kind. It may
          change, be unavailable, or be shut down, and content may be lost. To the extent the law allows, the
          maintainer is not liable for any loss arising from your use of the site. Nothing in these terms limits
          liability that cannot be limited by law.
        </p>

        <h2>Changes and governing law</h2>
        <p>
          These terms may change; the date at the top says when they last did. Continuing to use the site after a
          change means you accept it. These terms are governed by the law of England and Wales.
        </p>
      </div>
    </div>
  )
}
